name: Newman Run

on:
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create dir for report
        run: |
          mkdir testArtifacts

        #Config environement
      - name: Install Newman 
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run Test
        run: newman run ServerRest.postman_collection.json -e ServerRest_env.postman_environment.json -r cli,htmlextra

      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: newman
